# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://www.xponenthub.com
title: XponentHub | Home Page
email: support@xponenthub.com
author: XponentHub
description: > # "Write an awesome description for your new site here. 
  You can edit this line in _config.yml. It will appear in your document 
  head meta (for Google search results) and in your feed.xml site 
  description.
copyright: 'Copyright &copy; 2015 XponentHub. All Rights Reserved.'
credits: 'Credits: Landing Page is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com/">Start Bootstrap</a>.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: facebook
    url: https://www.facebook.com/XponentHub-1028786677177888
  - title: google-plus
    url: https://plus.google.com/108864224100967420521
  - title: github
    url: https://github.com/xponenthub
